export enum ProductType {
  CLOTHING = "CLOTHING",
  HOME_LIVING = "HOME_LIVING",
  ACCESSORY = "ACCESSORY",
  HANDMADE = "HANDMADE",
  VINTAGE = "VINTAGE",
  CRAFT_SUPPLIES = "CRAFT_SUPPLIES",
  JEWELRY = "JEWELRY",
  PET_PRODUCTS = "PET_PRODUCTS",
  ART_COLLECTABLES = "ART_COLLECTABLES",
  CHILDREN = "CHILDREN",
}

export enum ProductStatus {
  HOLD = "HOLD",
  ACTIVE = "ACTIVE",
  SOLD = "SOLD",
  DELETE = "DELETE",
}

export enum SHippingTimeType {
  TURBO = "TURBO",
  FAST = "FAST",
  SLOW = "SLOW",
}
